# Generated by Django 3.2.4 on 2022-01-16 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contact_me',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=265)),
                ('email', models.EmailField(blank=True, error_messages={'invalid_choice': 'you custom error message'}, help_text='Use email format', max_length=100, null=True, unique=True)),
                ('subject', models.CharField(max_length=150)),
                ('company', models.CharField(max_length=150)),
                ('project_Summary', models.CharField(max_length=1500)),
            ],
        ),
    ]
