# Generated by Django 3.2.4 on 2022-01-28 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_me',
            name='email',
            field=models.EmailField(blank=True, error_messages={'invalid_choice': 'you custom error message'}, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='contact_me',
            name='project_Summary',
            field=models.TextField(max_length=1500),
        ),
    ]
