# Generated by Django 3.2.4 on 2022-02-01 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfo', '0002_auto_20220128_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_me',
            name='project_Summary',
            field=models.CharField(max_length=1500),
        ),
    ]
