# Generated by Django 4.0.5 on 2022-07-13 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfo', '0003_alter_contact_me_project_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_me',
            name='project_Summary',
            field=models.TextField(max_length=1500),
        ),
    ]
