# Generated by Django 4.0.5 on 2022-07-14 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfo', '0004_alter_contact_me_project_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_me',
            name='email',
            field=models.EmailField(error_messages={'invalid_choice': 'you custom error message'}, max_length=100),
        ),
    ]
