# Generated by Django 4.0.5 on 2022-07-28 05:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('portfo', '0010_alter_post_created_on_alter_post_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 28, 5, 20, 58, 981108, tzinfo=utc)),
        ),
    ]
