# Generated by Django 4.0.5 on 2022-07-31 07:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('portfo', '0014_post_img_alter_post_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Img',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 31, 7, 58, 23, 446289, tzinfo=utc)),
        ),
    ]
