# Generated by Django 4.0.5 on 2022-07-31 08:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('portfo', '0015_alter_post_img_alter_post_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 31, 8, 46, 41, 722122, tzinfo=utc)),
        ),
    ]
