# Generated by Django 4.0.5 on 2022-08-01 10:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('portfo', '0018_alter_post_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Img',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 1, 10, 20, 33, 826808, tzinfo=utc)),
        ),
    ]
