# Generated by Django 4.2.2 on 2023-09-15 10:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfo', '0020_alter_post_img_alter_post_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 15, 10, 3, 55, 480887, tzinfo=datetime.timezone.utc)),
        ),
    ]
