# Generated by Django 4.2.2 on 2023-09-20 17:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfo', '0022_alter_post_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 20, 17, 34, 39, 244377, tzinfo=datetime.timezone.utc)),
        ),
    ]
